"""Run the whole pipeline end-to-end on synthetic data.

    python run_demo.py

This verifies the installation and shows what each stage reports. It is NOT a
backtest result: the data is generated by `tests/fixtures/make_fixture.py`, so
the P&L below describes a random walk, not SPY. Replace the fixture with a real
dataset (see `data/adapters/feasibility_check.py`) before any number here means
anything.
"""
from __future__ import annotations

from datetime import date

import numpy as np

from backtest.engine import run_walk_forward
from data.adapters.feasibility_check import assess
from data.events import EventCalendar
from features.splits import describe_folds, walk_forward_folds
from labels.audit import audit_sample
from models.baselines import train_gradient_boosting
from pipeline import build_dataset
from reports.monthly_report import dte_bucket, monthly_report, render
from tests.fixtures.make_fixture import make_fixture, to_bars

CFG = {"min_oi": 100, "min_credit": 0.20, "slippage_per_leg": 0.025}


def demo_calendar() -> EventCalendar:
    years = range(2022, 2028)
    return EventCalendar(
        dates={
            "FOMC": frozenset(date(y, m, 15) for y in years for m in (3, 6, 9, 12)),
            "CPI": frozenset(date(y, m, 12) for y in years for m in (2, 8)),
            "JOBS": frozenset(date(y, m, 5) for y in years for m in (4, 10)),
        },
        coverage_start=date(2020, 1, 1), coverage_end=date(2030, 1, 1),
        source="demo")


def banner(text: str) -> None:
    print(f"\n{'=' * 66}\n  {text}\n{'=' * 66}")


def main() -> int:
    print(__doc__)

    banner("1. GENERATE SYNTHETIC DATA")
    underlying, vix, chain = make_fixture(n_days=1100, seed=7, warmup_days=300)
    print(f"  {len(underlying):,} price bars, {len(chain):,} option quotes")
    print(f"  {underlying[0][0].date()} .. {underlying[-1][0].date()}")

    banner("2. FEASIBILITY CHECK  (always run this first on real data)")
    print(assess(chain[:20000]).render())

    banner("3. BUILD DATASET")
    dataset, report = build_dataset(
        chain, to_bars(underlying), to_bars(vix, "^VIX"),
        config=CFG, calendar=demo_calendar(),
        fees_per_spread=0.026, slippage=0.02)
    print(report.render())
    if len(dataset) < 40:
        print("\n  too few rows to model; stopping here")
        return 1

    banner("4. WALK-FORWARD SPLITS  (embargo enforced)")
    folds = walk_forward_folds(dataset.entry_dates,
                               dataset.entry_dates[len(dataset) // 3],
                               dataset.entry_dates[-1])
    for row in describe_folds(dataset.entry_dates, folds):
        print(f"  fold {row['fold']}: train {row['train_n']:>4} rows "
              f"({row['train_start'].date()}..{row['train_end'].date()})  "
              f"test {row['test_n']:>4} rows  gap {row['gap_days']}d")

    banner("5. MANUAL AUDIT SAMPLE  (spec requires a human to read 50)")
    audit = audit_sample(dataset.outcomes, n=3, seed=42)
    print(audit["text"])
    print(f"\n  consistency checks across the sample: "
          f"{'all clean' if audit['clean'] else audit['failures']}")

    banner("6. WALK-FORWARD BACKTEST  (gradient boosting baseline)")
    result = run_walk_forward(
        dataset, folds, model_fn=train_gradient_boosting,
        commission_per_contract=0.65, min_trades_for_threshold=10,
        model_version="gb_demo_v1")
    for f in result.folds:
        print(f"  fold {f.fold}: threshold {f.threshold:.2f}  "
              f"traded {f.n_traded:>3}/{f.n_test}  "
              f"net ${f.trading.get('total_pnl', 0):>10,.2f}"
              + (f"  KILLED: {f.killed}" if f.killed else ""))

    if len(result.ledger) < 2:
        print("\n  the frozen threshold selected too few trades to report on.")
        print("  That is a valid outcome -- the system is allowed to stand down.")
        return 0

    banner("7. REPORT")
    print(render(monthly_report(
        result.ledger.trades, result.probabilities, result.labels,
        pnl=result.ledger.pnl_series(),
        groups={"dte": [dte_bucket(t.dte) for t in result.ledger.trades],
                "exit": [t.exit_reason for t in result.ledger.trades]})))

    print("\n  Reminder: synthetic data. These numbers describe a random walk.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
